(lang dune 3.12)

(name mazesolver)

(generate_opam_files false)

(source
 (github username/reponame))

(authors "Harry K")

(maintainers "Harry K")

(license LICENSE)

(documentation https://url/to/documentation)
